### ISSUE TITLE
ChunkAnimator 1.16.5-1.2.0 fails to load on DEDICATED_SERVER side

### ISSUE THREAD

**Issue by sandalle** [Harleyoc1/ChunkAnimator#4]
**Notice**
If you are opening an issue **for any other reason** than to report a bug or request a new feature, you should probably be using the [Discussions](https://github.com/Harleyoc1/Chunk-Animator/discussions) tab.

Also, thank you for working on porting this mod to MC 1.16. :)

**Describe the bug**
This mod on a dedicated server causes it to crash (SIDED issue).

**To Reproduce**
1. Install this mod on a dedicated server
2. Try to start the server
3. See error

**Expected Behavior**
Server should be able to start, if the mod detects a SIDED it does nothing on (e.g. `DEDICATED_SERVER`), then it should just do a NOOP and continue.

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 1.16.5-36.0.21
 - Chunk Animator Version: 1.16.5-1.2.0

**Additional context**
Error in logs:
```
[10:51:02] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Chunk Animator (chunkanimator) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {re:classloading}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.21.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.21.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.21.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.21.jar:?] {re:classloading}
```

**Comment by koderian** [comment]
uhm, why would you install this mod on a server?

**Comment by Harleyoc1** [comment]
I knew I should've tested this, thanks for bringing it up. I'll change it to do nothing if it's loaded on server side.

**Comment by Harleyoc1** [comment]
> uhm, why would you install this mod on a server?

If you drag a pack of mods into a dedicated server (assuming this was how this happened) it's not ideal for it to just crash, best it's just ignored instead to remove the hassle of sifting through the client mods.

**Comment by sandalle** [comment]
> 
> 
> uhm, why would you install this mod on a server?

For modpacks, and convenience of setting up servers, usually the same client mods/configs are just copied to a dedicated server. I _do_ make a separate serverpack for my modpack for people to download and have disabled specific mods in the past for the serverpack, but the mods _should_ "just work", or at least do nothing and not crash, whether loaded on a client or server. ;)

Also, Forge Mod Loader (FML) tends to complain/warn when your client modlist and server modlist don't _exactly_ agree with what they have loaded.
